spring:
  jpa:
    hibernate.naming.physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  datasource:
    url: jdbc:postgresql://localhost:5432/papers-please
    username: binneling
    password: hemmelig
    driver-class-name: org.postgresql.Driver

server:
  port : 8081

kafka:
  immigrant:
    producer:
      clientId: binneling
      broker-url: http://localhost:29092
      acks-config: all
      topics:
        ZERO: itverket-immigration-0
        ONE: itverket-immigration-1
        TWO: itverket-immigration-2
        THREE: itverket-immigration-3
  immigration-result:
    consumer:
      topic: itverket-immigration-result
      broker-url: http://localhost:29092
      group-id: placeholder